services:
  db:
    container_name: db-cycle
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: web-cycle
    build: .
    command: gunicorn cycle.wsgi:application --bind 0.0.0.0:8000 --workers=2 --timeout 600 --reload
    env_file:
      - project.env
    ports:
      - "8000"
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media
      - .:/home/app/web

  mosquitto:
    container_name: mosquitto-cycle
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883" 
      - "9001:9001" 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    expose:
      - 1883
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "hello", "-u", "avyakt", "-P", "3.14159265358"]
      interval: 30s
      timeout: 10s
      retries: 3


  nginx:
    container_name: nginx-cycle
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "1729:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  staticfiles:
  mediafiles:
